### ISSUE TITLE
Warning:  Undefined array key 3 in ....

### ISSUE THREAD

**Issue by mlcampbe** [mprins/pagequery#31]
**Describe the bug**
I've had PageQuery working for many months now but I just started seeing this warning when using it:

**Warning:  Undefined array key 3 in /<path>/lib/plugins/pagequery/PageQuery.php on line 840, referer: https://<hostname>:8443/dokuwiki/doku.php?id=blank**

Seems like I had this problem many months back but hacked it somehow to get around it. I'm not sure what caused it to re-surface though. For now I've hardcoded the DOKU_E_LEVEL=0 to ignore all php error related output. This fixes the problem and pagequery works fine but this is not a good answer. 

**To Reproduce**
Steps to reproduce the behaviour:
Use the following entry:
{{pagequery>@:notes .*; 
  sort=a,title;  
  spelldate; 
  label=A-Z List of All Pages; 
  showcount;  
  display=title; 
  snippet=plain,10,w30 
  filter=^id:sidebar; 
  group; 
  cols=1; 
  proper; 
  border=inside; 
  hidestart; 
  bullet=disc }}

**Expected behaviour**
Should not see the error/warning

**Screenshots**

**Desktop (please complete the following information):**
 - php version: PHP Version 8.4.1
 - dokuwiki version: 2024-02-06b "Kaos"
 - Browser [e.g. chrome, firefox, safari] chrome(v131) and firefox(v133)
 - Version [e.g. 2023-06-05]

**Additional context**

** error log **

```
**Warning:  Undefined array key 3 in /<path>/lib/plugins/pagequery/PageQuery.php on line 840, referer: https://<hostname>:8443/dokuwiki/doku.php?id=blank**
```

** debug log **

```
2024-12-16 19:26:44
E_WARNING: Undefined array key 5
/Users/name/Sites/dokuwiki/lib/plugins/pagequery/PageQuery.php(840)
#0 /Users/name/Sites/dokuwiki/lib/plugins/pagequery/PageQuery.php(840): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/Users/name...', 840)
#1 /Users/name/Sites/dokuwiki/lib/plugins/pagequery/PageQuery.php(56): PageQuery->renderAsHtmltable(Array, Array, 26)
#2 /Users/name/Sites/dokuwiki/lib/plugins/pagequery/syntax.php(307): PageQuery->renderAsHtml('table', Array, Array, 26)
#3 /Users/name/Sites/dokuwiki/inc/parser/renderer.php(126): syntax_plugin_pagequery->render('xhtml', Object(renderer_plugin_xbr), Array)
#4 /Users/name/Sites/dokuwiki/inc/parserutils.php(691): Doku_Renderer->plugin('pagequery', Array, 5, '{{pagequery>@:n...')
#5 /Users/name/Sites/dokuwiki/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
#6 /Users/name/Sites/dokuwiki/inc/parserutils.php(97): p_cached_output('/Users/name...', 'xhtml', 'sidebar')
#7 /Users/name/Sites/dokuwiki/inc/template.php(1658): p_wiki_xhtml('sidebar', '', false)
#8 /Users/name/Sites/dokuwiki/lib/tpl/dokuwiki/main.php(44): tpl_include_page('sidebar', true, true)
#9 /Users/name/Sites/dokuwiki/inc/actions.php(30): include('/Users/name...')
#10 /Users/name/Sites/dokuwiki/doku.php(131): act_dispatch()
#11 {main}
```

**Comment by mprins** [comment]
The code seems to be expecting some data where there is none; I do not see this warning in any of my logs.

please see: https://github.com/mprins/pagequery/issues/13

**Comment by mlcampbe** [comment]
Ok, I played around with it and have gotten it working but still think there may be a problem somewhere. I am using PageQuery as my sidebar table of contents since I have just a handful of pages in my wiki. The above pagequery setup works fine if the sidebar.txt file contains ONLY that info. However, if I add ~~NOCACHE~~ to the sidebar.txt file then the problem occurs.

I also have the addnewpage plugin installed which I had added after the pagequery plugin in the sidebar.txt. If that is present in the file then the problem occurs. 

I can add plain text to the sidebar.txt file and the pagequery plugin works fine but if I add anything else it seems to break. I can understand another plugin causing issues but would have expected NOCACHE to work.

I'll play around with the php code and see if I can gather any more info.

**Comment by mlcampbe** [comment]
Further investigation shows that the problem has something to do with sorting and grouping.  If I remove both my sort and group options then no errors and all works fine. It still works fine if I add the group option only but that does nothing as there are no breaks to group the content by. 

Leaving the group option enabled and using the example from the docs if I add "sort=cyear,cmonth,name" then the error occurs 30+ times:
Warning: Undefined array key 3 in /<path>Sites/dokuwiki/lib/plugins/pagequery/PageQuery.php on line 840

Similarly if I change to sort=a the same problem occurs. Once on line 359 and then many times on line 840.

For now I have a couple of fixes:
1 - Disable the grouping function completely
2 - Remove the NOCACHE and NEWPAGE options from the sidebar.txt

**Comment by mlcampbe** [comment]
I believe I have fixed the problem with some edits to the PageQuery.php file. I tried to submit a PR and got permission denied. I'm not a github expert but is there something that you need to do to allow me to submit the PR?

**Comment by mprins** [comment]
There is nothing I can do, this is a public repository, anyone can fork it, create a branch in their fork for and submit a pr
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by mprins** [comment]
resolved in https://github.com/mprins/pagequery/pull/32
